// TODO F1: regenerated by `pnpm db:types` from the linked Supabase project.
// This stub makes `pnpm build` succeed before F1 runs. After F1, the file
// contains the full Database type derived from the cloud schema.
export type Database = unknown;
